### ISSUE TITLE
volodya - Some oracles will be validated incorrectly

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-bond-judging#2]
volodya

medium

# Some oracles will be validated incorrectly

## Summary
Oracles with `priceDecimals` equal to `-24` will be validated incorrectly

## Vulnerability Detail
According to the comments in the code price difference can be `-24` but its not the same in the code
>        // Check price decimals in reasonable range
>        // These bounds are quite large and it is unlikely any combination of tokens
>        // will have a price difference larger than 10^24 in either direction.

```solidity
        if (priceDecimals < -23 || priceDecimals > 24) revert Auctioneer_InvalidParams();
```
[BondBaseOSDA.sol#L269](https://github.com/sherlock-audit/2023-02-bond/blob/main/bonds/src/bases/BondBaseOSDA.sol#L269)

```solidity
        if (priceDecimals < -23 || priceDecimals > 24) revert Auctioneer_InvalidParams();
```

[BondBaseOFDA.sol#L262](https://github.com/sherlock-audit/2023-02-bond/blob/main/bonds/src/bases/BondBaseOFDA.sol#L262)

## Impact
Oracles that are supposed to be fit will not be in `BondBaseOFDA.sol` and `BondBaseOSDA.sol`
## Tool used

Manual Review

## Recommendation
```diff
-        if (priceDecimals < -23 || priceDecimals > 24) revert Auctioneer_InvalidParams();
+        if (priceDecimals < -24 || priceDecimals > 24) revert Auctioneer_InvalidParams();
```

**Comment by Oighty** [comment]
Issue fixed here: https://github.com/Bond-Protocol/bonds/pull/56

**Comment by xiaoming9090** [comment]
Fixed in https://github.com/Bond-Protocol/bonds/pull/56
