### ISSUE TITLE
xiaoming90 - Lack of validation in `setPair`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-bond-judging#24]
xiaoming90

medium

# Lack of validation in `setPair`

## Summary

The `quoteToken_` or `payoutToken_` can be set to zero address in the Oracle, which does not conform to the properties of the Bond market.

## Vulnerability Detail

In DEFI, a zero address usually means no token OR refers to native ETH. From the Bond Aggregator (refer to Line 81 below), it was understood that the Bond market does not accept zero address as either of the token pairs (`payoutToken_` or `quoteToken_`).

This in turn mean that the Bond market does not support native ETH

```solidity
File: BondAggregator.sol
75:     function registerMarket(ERC20 payoutToken_, ERC20 quoteToken_)
76:         external
77:         override
78:         returns (uint256 marketId)
79:     {
80:         if (!_whitelist[msg.sender]) revert Aggregator_OnlyAuctioneer();
81:         if (address(payoutToken_) == address(0) || address(quoteToken_) == address(0))
82:             revert Aggregator_InvalidParams();
83:         marketId = marketCounter;
84:         marketsToAuctioneers[marketId] = IBondAuctioneer(msg.sender);
85:         marketsForPayout[address(payoutToken_)].push(marketId);
86:         marketsForQuote[address(quoteToken_)].push(marketId);
87:         ++marketCounter;
88:     }
```

However, this property was not consistently applied to the `BondBaseOracle.setPair` function. It is possible for the owner to set the `quoteToken_` or `payoutToken_` to a zero address.

```solidity
File: BondBaseOracle.sol
133:     function setPair(
134:         ERC20 quoteToken_,
135:         ERC20 payoutToken_,
136:         bool supported_,
137:         bytes calldata oracleData_
138:     ) external onlyOwner {
139:         // Toggle pair status
140:         supportedPairs[quoteToken_][payoutToken_] = supported_;
141: 
142:         // Update oracle data for particular implementation
143:         _setPair(quoteToken_, payoutToken_, supported_, oracleData_);
144: 
145:         // Emit event
146:         emit PairUpdated(quoteToken_, payoutToken_, supported_);
147:     }
```

## Impact

This is a potential pitfall as it might cause confusion to the developer or auditor if there is a pair with `quoteToken_` or `payoutToken_` set to zero address in the Oracle. They might assume that a USDC/Native ETH pair exists.

## Code Snippet

https://github.com/sherlock-audit/2023-02-bond/blob/main/bonds/src/bases/BondBaseOracle.sol#L133

## Tool used

Manual Review

## Recommendation

Implement additional validation check to ensure that `payoutToken_` or `quoteToken_` is not set to zero address.

```diff
function setPair(
    ERC20 quoteToken_,
    ERC20 payoutToken_,
    bool supported_,
    bytes calldata oracleData_
) external onlyOwner {
+    if (address(payoutToken_) == address(0) || address(quoteToken_) == address(0))
+    	revert Aggregator_InvalidParams();

    // Toggle pair status
    supportedPairs[quoteToken_][payoutToken_] = supported_;

    // Update oracle data for particular implementation
    _setPair(quoteToken_, payoutToken_, supported_, oracleData_);

    // Emit event
    emit PairUpdated(quoteToken_, payoutToken_, supported_);
}
```

**Comment by Oighty** [comment]
Issue fixed here: https://github.com/Bond-Protocol/bonds/pull/55

**Comment by xiaoming9090** [comment]
Fixed in https://github.com/Bond-Protocol/bonds/pull/55/files
