### ISSUE TITLE
xiaoming90 - Inconsistencies within the `payoutFor` function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-bond-judging#26]
xiaoming90

medium

# Inconsistencies within the `payoutFor` function

## Summary

Inconsistencies within the `payoutFor` function were observed. The function does not revert when there is insufficient capacity for the number of payout tokens they are expected to receive when depositing a certain number of quote tokens. This gives the caller an incorrect state of the current market.

## Vulnerability Detail

> This issue affects FPA, OFDA, and OSDA

Within the `purchaseBond` function, the function will revert, and the users will not be able to purchase the bond when any of the conditions is met:

- The payout exceeds the max payout
- Amount/payout is greater than the capacity remaining

```solidity
File: BondBaseFPA.sol
262:     function purchaseBond(
263:         uint256 id_,
264:         uint256 amount_,
265:         uint256 minAmountOut_
266:     ) external override returns (uint256 payout) {
..SNIP
286:         // Markets have a max payout amount per transaction
287:         if (payout > market.maxPayout) revert Auctioneer_MaxPayoutExceeded();
..SNIP..
297:         // If amount/payout is greater than capacity remaining, revert
298:         if (market.capacityInQuote ? amount_ > market.capacity : payout > market.capacity)
299:             revert Auctioneer_NotEnoughCapacity();
300:         // Capacity is decreased by the deposited or paid amount
301:         market.capacity -= market.capacityInQuote ? amount_ : payout;
..SNIP..
307:     }
```

It was observed that there are some inconsistencies within the `payoutFor` function. The function will revert when the payout exceeds the max payout. However, it does not revert if the amount/payout is greater than the capacity remaining.

```solidity
File: BondBaseFPA.sol
350:     function payoutFor(
351:         uint256 amount_,
352:         uint256 id_,
353:         address referrer_
354:     ) public view override returns (uint256) {
355:         // Calculate the payout for the given amount of tokens
356:         uint256 fee = amount_.mulDiv(_teller.getFee(referrer_), ONE_HUNDRED_PERCENT);
357:         uint256 payout = (amount_ - fee).mulDiv(markets[id_].scale, marketPrice(id_));
358: 
359:         // Check that the payout is less than or equal to the maximum payout,
360:         // Revert if not, otherwise return the payout
361:         if (payout > markets[id_].maxPayout) {
362:             revert Auctioneer_MaxPayoutExceeded();
363:         } else {
364:             return payout;
365:         }
366:     }
```

Assume the following:

- maxPayout = 100 Bond Tokens (DAI)
- market.capacity = 50 Bond Tokens (DAI) left
- payout = 70 Bond Tokens (DAI) should be issued to the users

Assume that Alice calls the `payoutFor` function for a certain amount of quote tokens. The function will return `70 Bond Tokens (DAI)` and will not revert because `payout` is lower than the `maxPayout`.

This makes Alice believe she can obtain `70 Bond Tokens (DAI)` if she calls the `purchaseBond` function. However, when she calls the `purchaseBond` function, the function reverts because of insufficient capacity.

## Impact

Inconsistencies within the protocol can cause various issues, especially for the external or third-party protocol that relies on protocol's interfaces to determine the correct state of the protocol they are integrating with. Also, callers relying on the `payoutFor` result might wrongly assume that their `purchaseBond` transaction will go through when there is insufficient capacity, incurring unnecessary delay or missed opportunity during trading.

## Code Snippet

https://github.com/sherlock-audit/2023-02-bond/blob/main/bonds/src/bases/BondBaseFPA.sol#L350

https://github.com/sherlock-audit/2023-02-bond/blob/main/bonds/src/bases/BondBaseOFDA.sol#L470

https://github.com/sherlock-audit/2023-02-bond/blob/main/bonds/src/bases/BondBaseOSDA.sol#L542

## Tool used

Manual Review

## Recommendation

Update the `payoutFor` function to revert when there is insufficient capacity.

```diff
function payoutFor(
    uint256 amount_,
    uint256 id_,
    address referrer_
) public view override returns (uint256) {
    // Calculate the payout for the given amount of tokens
    uint256 fee = amount_.mulDiv(_teller.getFee(referrer_), ONE_HUNDRED_PERCENT);
    uint256 payout = (amount_ - fee).mulDiv(markets[id_].scale, marketPrice(id_));

    // Check that the payout is less than or equal to the maximum payout,
    // Revert if not, otherwise return the payout
    if (payout > markets[id_].maxPayout) {
        revert Auctioneer_MaxPayoutExceeded();
+   } else if (market[id_].capacityInQuote ? amount_ > market[id_].capacity : payout > market[id_].capacity) {
+		revert Auctioneer_NotEnoughCapacity();
    } else {
        return payout;
    }
}
```

**Comment by UsmannK** [comment]
Escalate for 10 USDC

Watson claims that this view function may return `payout` amounts that are higher than the `capacity` remaining in the contract, instead of reverting. However, this inconsistency cannot lead to loss of funds and does not qualify for a Medium rating. 

This is because the actual `purchaseBond` function reverts if `payout > capacity`. See:
https://github.com/sherlock-audit/2023-02-bond/blob/8a326a4b39fdaf9eaf5911cfd3e9676a83c24a58/bonds/src/bases/BondBaseFPA.sol#L298-L299


Watson claims impact is `callers relying on the payoutFor result might wrongly assume that their purchaseBond transaction will go through when there is insufficient capacity, incurring unnecessary delay or missed opportunity during trading.`

However, their trade will simply revert and no funds will be lost. If the trade were to go through at an unexpected payout, this would be medium. However, because no funds will be lost (except a small amount of gas), by the Sherlock rules this is a low and not a medium. The criteria are as follows:

`Medium: There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost. `

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Watson claims that this view function may return `payout` amounts that are higher than the `capacity` remaining in the contract, instead of reverting. However, this inconsistency cannot lead to loss of funds and does not qualify for a Medium rating. 
> 
> This is because the actual `purchaseBond` function reverts if `payout > capacity`. See:
> https://github.com/sherlock-audit/2023-02-bond/blob/8a326a4b39fdaf9eaf5911cfd3e9676a83c24a58/bonds/src/bases/BondBaseFPA.sol#L298-L299
> 
> 
> Watson claims impact is `callers relying on the payoutFor result might wrongly assume that their purchaseBond transaction will go through when there is insufficient capacity, incurring unnecessary delay or missed opportunity during trading.`
> 
> However, their trade will simply revert and no funds will be lost. If the trade were to go through at an unexpected payout, this would be medium. However, because no funds will be lost (except a small amount of gas), by the Sherlock rules this is a low and not a medium. The criteria are as follows:
> 
> `Medium: There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost. `

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Oighty** [comment]
Issue fixed here: https://github.com/Bond-Protocol/bonds/pull/48

**Comment by xiaoming9090** [comment]
Fixed in https://github.com/Bond-Protocol/bonds/pull/48

**Comment by hrishibhat** [comment]
Escalation accepted

Considering that the impact is only on the view function and does not cause problems to the internal logic or loss of funds, considering this issue as low

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Considering that the impact is only on the view function and does not cause problems to the internal logic or loss of funds, considering this issue as low

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
