### ISSUE TITLE
Bauer - Use call() instead of transfer() on an address payable

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-bond-judging#37]
Bauer

medium

# Use call() instead of transfer() on an address payable

## Summary
The use of the deprecated transfer() function for an payable address will inevitably make the transaction

## Vulnerability Detail
The transfer() and send() functions forward a fixed amount of 2300 gas. Historically, it has often been recommended to use these functions for value transfers to guard against reentrancy attacks. However, the gas cost of EVM instructions may change significantly during hard forks which may break already deployed contract systems that make fixed assumptions about gas costs. For example. EIP 1884 broke several existing smart contracts due to a cost increase of the SLOAD instruction.

```solidity

    function emergencyWithdraw(ERC20 token_) external override onlyOwner {
        // Confirm that the token is a contract
        if (address(token_).code.length == 0 && address(token_) != address(0))
            revert BatchAuction_InvalidParams();

        // If token address is zero, withdraw ETH
        if (address(token_) == address(0)) {
            payable(owner()).transfer(address(this).balance);
        } else {
            token_.safeTransfer(owner(), token_.balanceOf(address(this)));
        }
    }

```
## Impact
The use of the deprecated transfer() function for an address will inevitably make the transaction fail when:

The claimer smart contract does not implement a payable function.
The claimer smart contract does implement a payable fallback which uses more than 2300 gas unit.
The claimer smart contract implements a payable fallback function that needs less than 2300 gas units but is called through proxy, raising the call's gas usage above 2300.
Additionally, using higher than 2300 gas might be mandatory for some multisig wallets.

## Code Snippet
https://github.com/sherlock-audit/2023-02-bond/blob/main/bonds/src/BondBatchAuctionV1.sol#L287

## Tool used

Manual Review

## Recommendation
Use call() instead of transfer(), but be sure to respect the CEI pattern and/or add re-entrancy guards, as several hacks already happened in the past due to this recommendation not being fully understood.

More info on; https://swcregistry.io/docs/SWC-134

**Comment by UsmannK** [comment]
Escalate for 10 USDC

This issue is a case of possible Admin misconfiguration. This is generally not grounds for a valid medium as per Sherlock guidance: https://discord.com/channels/812037309376495636/881726370370158592/1089164320115523604

Watson claims that using "transfer()" can brick `emergencyWithdrawal`s when the transfer recipient uses high gas in its ETH receiver callback function.

The `emergencyWithdrawal()` function can only be called by the owner and the destination address can be changed by the owner at any time. If the current owner does not use gas conservatively enough to satisfy `transfer()`, they may simply change the owner to a new contract that can do so. There is no case where loss of funds can occur as a result of this admin misconfiguration.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This issue is a case of possible Admin misconfiguration. This is generally not grounds for a valid medium as per Sherlock guidance: https://discord.com/channels/812037309376495636/881726370370158592/1089164320115523604
> 
> Watson claims that using "transfer()" can brick `emergencyWithdrawal`s when the transfer recipient uses high gas in its ETH receiver callback function.
> 
> The `emergencyWithdrawal()` function can only be called by the owner and the destination address can be changed by the owner at any time. If the current owner does not use gas conservatively enough to satisfy `transfer()`, they may simply change the owner to a new contract that can do so. There is no case where loss of funds can occur as a result of this admin misconfiguration.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Oighty** [comment]
Issue fixed here: https://github.com/Bond-Protocol/bonds/pull/49

**Comment by xiaoming9090** [comment]
Fixed in https://github.com/Bond-Protocol/bonds/pull/49

**Comment by hrishibhat** [comment]
Escalation accepted

Considering this issue as low, since this is an admin function

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Considering this issue as low, since this is an admin function

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
