### ISSUE TITLE
usmannk - Creating bonds will fail for some valid tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-bond-judging#42]
usmannk

medium

# Creating bonds will fail for some valid tokens

## Summary

The `createMarket` operation in the Bond Base contracts calls the `decimals()` function on the quote and payout tokens. However, EIP20 specifies that the `decimals()` function is optional for ERC20 tokens.

## Vulnerability Detail

Creating bonds for many valid ERC20s will result in reverts.

https://github.com/sherlock-audit/2023-02-bond/blob/main/bonds/src/bases/BondBaseFPA.sol#L123-L125

## Impact

It will be impossible to create bonds for a large class of valid tokens.

## Tool used

Manual Review

## Recommendation

Allow bond initializers to specify decimal amounts in the parameters.

**Comment by UsmannK** [comment]
Escalate for 10 USDC

Sponsor stated that the protocol should be compatible with: `ERC20: any`. There was no way for watsons or Sherlock to know that this actually excluded valid ERC20s. Watson identified an `OPTIONAL` ERC20 field that the codebase treats as `REQUIRED`, causing reverts.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Sponsor stated that the protocol should be compatible with: `ERC20: any`. There was no way for watsons or Sherlock to know that this actually excluded valid ERC20s. Watson identified an `OPTIONAL` ERC20 field that the codebase treats as `REQUIRED`, causing reverts.
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid medium
While this could be technically correct, as the Sponsor commented this is an intentional design for scaling reasons. 
Also, it is safe to assume all Standard ERC20's will return decimals. 
In the case of the optional tokens, it can be considered as an additional feature lost. Considering this issue as low.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Not a valid medium
> While this could be technically correct, as the Sponsor commented this is an intentional design for scaling reasons. 
> Also, it is safe to assume all Standard ERC20's will return decimals. 
> In the case of the optional tokens, it can be considered as an additional feature lost. Considering this issue as low. 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
